plugins:
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,codesize,naming,phpmd.xml"
exclude_patterns:
  - tests/**/*
  - "**/vendor/**/*"
